#############################################################################
# Makefile for building: reproductor-exe
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  reproductor/reproductor.pro
# Template: app
# Command: /home/user/Qt5.2.1/5.2.1/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile reproductor/reproductor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++ -Ireproductor -I../../../../Qt5.2.1/5.2.1/gcc/include -I../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets -I../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia -I../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets -I../../../../Qt5.2.1/5.2.1/gcc/include/QtXml -I../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork -I../../../../Qt5.2.1/5.2.1/gcc/include/QtGui -I../../../../Qt5.2.1/5.2.1/gcc/include/QtCore -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/user/Qt5.2.1/5.2.1/gcc -Wl,-rpath,/home/user/Qt5.2.1/5.2.1/gcc/lib -Wl,-rpath-link,/home/user/Qt5.2.1/5.2.1/gcc/lib
LIBS          = $(SUBLIBS) -L/home/user/Qt5.2.1/5.2.1/gcc/lib -lQt5MultimediaWidgets -lQt5Multimedia -lQt5Widgets -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/user/Qt5.2.1/5.2.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = reproductor/main.cpp \
		reproductor/mainwindow.cpp \
		reproductor/metadatadialog.cpp \
		reproductor/urldialog.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_metadatadialog.cpp \
		moc_urldialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		metadatadialog.o \
		urldialog.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_metadatadialog.o \
		moc_urldialog.o
DIST          = ../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/unix.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/linux.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-base.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/qconfig.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_config.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_post.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_pre.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_post.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qml_debug.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/warn_on.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resources.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/moc.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/opengl.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/uic.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exceptions.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/yacc.prf \
		../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/lex.prf \
		reproductor/reproductor/reproductor.pro \
		reproductor/reproductor/resources.qrc \
		reproductor/reproductor.pro
QMAKE_TARGET  = reproductor-exe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = reproductor-exe


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_metadatadialog.h ui_urldialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: reproductor/reproductor.pro ../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_pre.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/shell-unix.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/unix.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/linux.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-base.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-unix.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/qconfig.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_functions.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_config.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_post.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_pre.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resolve_config.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_post.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qml_debug.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/warn_on.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resources.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/moc.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/uic.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/thread.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exceptions.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/yacc.prf \
		../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/lex.prf \
		reproductor/reproductor.pro \
		reproductor/resources.qrc \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5MultimediaWidgets.prl \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Multimedia.prl \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Gui.prl \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Core.prl \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Network.prl \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Widgets.prl \
		/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Xml.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile reproductor/reproductor.pro
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_pre.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/shell-unix.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/unix.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/linux.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-base.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-unix.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/qconfig.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_functions.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_config.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++/qmake.conf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_post.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_pre.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resolve_config.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_post.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qml_debug.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/declarative_debug.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/warn_on.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resources.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/moc.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/opengl.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/uic.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/thread.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/testcase_targets.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exceptions.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/yacc.prf:
../../../../Qt5.2.1/5.2.1/gcc/mkspecs/features/lex.prf:
reproductor/reproductor.pro:
reproductor/resources.qrc:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5MultimediaWidgets.prl:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Multimedia.prl:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Gui.prl:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Core.prl:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Network.prl:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Widgets.prl:
/home/user/Qt5.2.1/5.2.1/gcc/lib/libQt5Xml.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile reproductor/reproductor.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/reproductor-exe1.0.0 || mkdir -p .tmp/reproductor-exe1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/resources.qrc .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/mainwindow.h reproductor/metadatadialog.h reproductor/urldialog.h .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/main.cpp reproductor/mainwindow.cpp reproductor/metadatadialog.cpp reproductor/urldialog.cpp .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/metadatadialog.ui reproductor/urldialog.ui .tmp/reproductor-exe1.0.0/ && (cd `dirname .tmp/reproductor-exe1.0.0` && $(TAR) reproductor-exe1.0.0.tar reproductor-exe1.0.0 && $(COMPRESS) reproductor-exe1.0.0.tar) && $(MOVE) `dirname .tmp/reproductor-exe1.0.0`/reproductor-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/reproductor-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: reproductor/resources.qrc \
		reproductor/resources/stop.png \
		reproductor/resources/play.png \
		reproductor/resources/pause.png \
		reproductor/resources/eject.png
	/home/user/Qt5.2.1/5.2.1/gcc/bin/rcc -name resources reproductor/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_metadatadialog.cpp moc_urldialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_metadatadialog.cpp moc_urldialog.cpp
moc_mainwindow.cpp: ../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMainWindow \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaPlayer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmultimedia.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediacontent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaresource.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QSharedDataPointer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QString \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QUrl \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/QVideoWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/qvideowidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediabindableinterface.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QDir \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdir.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfileinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QSlider \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QFileDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qfiledialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolBar \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenuBar \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenubar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenu.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenu \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMessageBox \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmessagebox.h \
		reproductor/metadatadialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaMetaData \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediametadata.h \
		reproductor/mainwindow.h
	/home/user/Qt5.2.1/5.2.1/gcc/bin/moc $(DEFINES) $(INCPATH) reproductor/mainwindow.h -o moc_mainwindow.cpp

moc_metadatadialog.cpp: ../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaPlayer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmultimedia.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediacontent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaresource.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QSharedDataPointer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QString \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QUrl \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaMetaData \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediametadata.h \
		reproductor/metadatadialog.h
	/home/user/Qt5.2.1/5.2.1/gcc/bin/moc $(DEFINES) $(INCPATH) reproductor/metadatadialog.h -o moc_metadatadialog.cpp

moc_urldialog.cpp: ../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		reproductor/urldialog.h
	/home/user/Qt5.2.1/5.2.1/gcc/bin/moc $(DEFINES) $(INCPATH) reproductor/urldialog.h -o moc_urldialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_metadatadialog.h ui_urldialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_metadatadialog.h ui_urldialog.h
ui_metadatadialog.h: reproductor/metadatadialog.ui
	/home/user/Qt5.2.1/5.2.1/gcc/bin/uic reproductor/metadatadialog.ui -o ui_metadatadialog.h

ui_urldialog.h: reproductor/urldialog.ui
	/home/user/Qt5.2.1/5.2.1/gcc/bin/uic reproductor/urldialog.ui -o ui_urldialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: reproductor/main.cpp reproductor/mainwindow.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMainWindow \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaPlayer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmultimedia.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediacontent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaresource.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QSharedDataPointer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QString \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QUrl \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/QVideoWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/qvideowidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediabindableinterface.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QDir \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdir.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfileinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QSlider \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QFileDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qfiledialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolBar \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenuBar \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenubar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenu.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenu \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMessageBox \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmessagebox.h \
		reproductor/metadatadialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaMetaData \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediametadata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QApplication \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qapplication.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreapplication.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qeventloop.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qguiapplication.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o reproductor/main.cpp

mainwindow.o: reproductor/mainwindow.cpp reproductor/mainwindow.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMainWindow \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaPlayer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmultimedia.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediacontent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaresource.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QSharedDataPointer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QString \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QUrl \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/QVideoWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/qvideowidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediabindableinterface.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QDir \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdir.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfileinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QSlider \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QFileDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qfiledialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolBar \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenuBar \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenubar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenu.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenu \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMessageBox \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmessagebox.h \
		reproductor/metadatadialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaMetaData \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediametadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o reproductor/mainwindow.cpp

metadatadialog.o: reproductor/metadatadialog.cpp reproductor/metadatadialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaPlayer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmultimedia.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediacontent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaresource.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QSharedDataPointer \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QString \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QUrl \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetaobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/QMediaMetaData \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtMultimedia/qmediametadata.h \
		ui_metadatadialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QApplication \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qapplication.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreapplication.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qeventloop.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qguiapplication.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qinputmethod.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QButtonGroup \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qbuttongroup.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QHeaderView \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qheaderview.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractitemview.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qabstractitemmodel.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qitemselectionmodel.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qstyleoption.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractspinbox.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvalidator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregularexpression.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qstyle.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabbar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qrubberband.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QListWidget \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlistwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlistview.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QPushButton \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qpushbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QSpacerItem
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metadatadialog.o reproductor/metadatadialog.cpp

urldialog.o: reproductor/urldialog.cpp reproductor/urldialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		ui_urldialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o urldialog.o reproductor/urldialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_metadatadialog.o: moc_metadatadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_metadatadialog.o moc_metadatadialog.cpp

moc_urldialog.o: moc_urldialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_urldialog.o moc_urldialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

