#############################################################################
# Makefile for building: reproductor-exe.app/Contents/MacOS/reproductor-exe
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  reproductor/reproductor.pro
# Template: app
# Command: /Applications/Qt/5.2.0/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile reproductor/reproductor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang -Ireproductor -I/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtXml.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Applications/Qt/5.2.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.2.0/clang_64/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtGui -framework QtCore -framework QtNetwork -framework QtWidgets -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Applications/Qt/5.2.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = reproductor/main.cpp \
		reproductor/mainwindow.cpp \
		reproductor/metadatadialog.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_metadatadialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		metadatadialog.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_metadatadialog.o
DIST          = /Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		reproductor/.qmake.stash \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/declarative_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		reproductor/reproductor/reproductor.pro \
		reproductor/reproductor/resources.qrc \
		reproductor/reproductor.pro
QMAKE_TARGET  = reproductor-exe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = reproductor-exe.app/Contents/MacOS/reproductor-exe

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile reproductor-exe.app/Contents/PkgInfo reproductor-exe.app/Contents/Resources/empty.lproj reproductor-exe.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_metadatadialog.h $(OBJECTS)  
	@test -d reproductor-exe.app/Contents/MacOS/ || mkdir -p reproductor-exe.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: reproductor/reproductor.pro /Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/declarative_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		reproductor/reproductor.pro \
		reproductor/resources.qrc \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtXml.framework/QtXml.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile reproductor/reproductor.pro
/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qml_debug.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/declarative_debug.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/lex.prf:
reproductor/reproductor.pro:
reproductor/resources.qrc:
/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtXml.framework/QtXml.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile reproductor/reproductor.pro

qmake_all: FORCE

reproductor-exe.app/Contents/PkgInfo: 
	@test -d reproductor-exe.app/Contents || mkdir -p reproductor-exe.app/Contents
	@$(DEL_FILE) reproductor-exe.app/Contents/PkgInfo
	@echo "APPL????" >reproductor-exe.app/Contents/PkgInfo
reproductor-exe.app/Contents/Resources/empty.lproj: 
	@test -d reproductor-exe.app/Contents/Resources || mkdir -p reproductor-exe.app/Contents/Resources
	@touch reproductor-exe.app/Contents/Resources/empty.lproj
	
reproductor-exe.app/Contents/Info.plist: 
	@test -d reproductor-exe.app/Contents || mkdir -p reproductor-exe.app/Contents
	@$(DEL_FILE) reproductor-exe.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,reproductor-exe,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/Info.plist.app >reproductor-exe.app/Contents/Info.plist
dist: 
	@test -d .tmp/reproductor-exe1.0.0 || mkdir -p .tmp/reproductor-exe1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/resources.qrc .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/mainwindow.h reproductor/metadatadialog.h .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/main.cpp reproductor/mainwindow.cpp reproductor/metadatadialog.cpp .tmp/reproductor-exe1.0.0/ && $(COPY_FILE) --parents reproductor/metadatadialog.ui .tmp/reproductor-exe1.0.0/ && (cd `dirname .tmp/reproductor-exe1.0.0` && $(TAR) reproductor-exe1.0.0.tar reproductor-exe1.0.0 && $(COMPRESS) reproductor-exe1.0.0.tar) && $(MOVE) `dirname .tmp/reproductor-exe1.0.0`/reproductor-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/reproductor-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r reproductor-exe.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: reproductor/resources.qrc \
		reproductor/resources/stop.png \
		reproductor/resources/pause.png \
		reproductor/resources/play.png \
		reproductor/resources/eject.png
	/Applications/Qt/5.2.0/clang_64/bin/rcc -name resources reproductor/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_metadatadialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_metadatadialog.cpp
moc_mainwindow.cpp: /Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QMediaPlayer \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qmediaplayer.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/QVideoWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/qvideowidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		reproductor/mainwindow.h
	/Applications/Qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) reproductor/mainwindow.h -o moc_mainwindow.cpp

moc_metadatadialog.cpp: /Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		reproductor/metadatadialog.h
	/Applications/Qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) reproductor/metadatadialog.h -o moc_metadatadialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_metadatadialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_metadatadialog.h
ui_metadatadialog.h: reproductor/metadatadialog.ui
	/Applications/Qt/5.2.0/clang_64/bin/uic reproductor/metadatadialog.ui -o ui_metadatadialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: reproductor/main.cpp reproductor/mainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QMediaPlayer \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qmediaplayer.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/QVideoWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/qvideowidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o reproductor/main.cpp

mainwindow.o: reproductor/mainwindow.cpp reproductor/mainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QMediaPlayer \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qmediaplayer.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/QVideoWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/qvideowidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o reproductor/mainwindow.cpp

metadatadialog.o: reproductor/metadatadialog.cpp reproductor/metadatadialog.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_metadatadialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metadatadialog.o reproductor/metadatadialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_metadatadialog.o: moc_metadatadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_metadatadialog.o moc_metadatadialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

